name: Scrape Earthquake Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install  # Ensures Playwright browsers are installed

      - name: Run Scraper
        run: python scrape_earthquake_data_nepal.py

      - name: Check for Changes
        run: |
          git diff --exit-code || echo "Changes detected, preparing to commit."

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add earthquakes.csv earthquakes.json earthquakes.geojson
          git commit -m "🔄 Weekly update: Earthquake data" || echo "No changes to commit"
          git push origin master || echo "No changes to push"
